config/routes.rb
Seminario::Application.routes.draw do
  get "pages/amcharts"

  get "pages/teste"

  get "pages/chart"

  resources :protocols

  resources :layers
  root :to => 'home#index'
end

app/models/layer.rb
class Layer < ActiveRecord::Base
	has_many :protocols
  attr_accessible :description, :name
	validates :name, :presence => true
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  belongs_to :layer, :counter_cache => true

  attr_accessible :description, :name, :layer_id
  validates :name, :layer, :presence => true
	validates :name, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  def index
		
    @layers = Layer.all
    
    respond_to do |format|
      format.html 
      format.json { render json: @layers }
    end
  end

  def show
    @layer = Layer.find(params[:id])

    	respond_to do |format|
      format.html 
      format.json { render json: @layer }
    end
  end

  def new
    @layer = Layer.new
    
    respond_to do |format|
      format.html 
      format.json { render json: @layer }
    end
  end

  def edit
    @layer = Layer.find(params[:id])
  end

  def create
    @layer = Layer.new(params[:layer])

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Camada criada com sucesso' }
        format.json { render json: @layer, status: :created, location: @layer }
      else
        format.html { render action: "new" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @layer = Layer.find(params[:id])

    respond_to do |format|
      if @layer.update_attributes(params[:layer])
        format.html { redirect_to @layer, notice: 'Camada atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
    @layer = Layer.find(params[:id])
    @layer.destroy

    respond_to do |format|
      format.html { redirect_to layers_url }
      format.json { head :no_content }
	  end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def amcharts
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  # GET /protocols
  # GET /protocols.json
  def index
    @protocols = Protocol.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @protocols }
    end
  end

  # GET /protocols/1
  # GET /protocols/1.json
  def show
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @protocol }
    end
  end

  # GET /protocols/new
  # GET /protocols/new.json
  def new
    @protocol = Protocol.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @protocol }
    end
  end

  # GET /protocols/1/edit
  def edit
    @protocol = Protocol.find(params[:id])
  end

  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = Protocol.new(params[:protocol])

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocol was successfully created.' }
        format.json { render json: @protocol, status: :created, location: @protocol }
      else
        format.html { render action: "new" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /protocols/1
  # PUT /protocols/1.json
  def update
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      if @protocol.update_attributes(params[:protocol])
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocols/1
  # DELETE /protocols/1.json
  def destroy
    @protocol = Protocol.find(params[:id])
    @protocol.destroy

    respond_to do |format|
      format.html { redirect_to protocols_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/views/home/index.html.erb
<h1 align="center">Seminário Redes de Comunicação de Dados</h1>
<br />

<ul>

		<h4><li>Jean de Almeida Lanziloti</li></h4>
		<h4><li>Cláudio Elizei Leal</li></h4>
		<h4><li>Fábio José</li></h4>
	
</ul>

app/views/home/index.html.haml
%h1 Seminário 

app/views/layers/_form.html.haml
= simple_form_for @layer, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :description, :input_html => { rows: 4 }
  .form-actions
    = f.button :submit, "Cadastrar", :class => 'btn btn-primary'
    = link_to "Cancelar", layers_path, :class => 'btn'

app/views/layers/edit.html.haml
- model_class = Layer
.page-header
  %h1 Editar Camada
= render :partial => "form"

app/views/layers/index.html.haml
.page-header
  %h1 Camadas
  = simple_form_for :search, :url => protocols_path, :method => :get do |f|
    = f.input :layer, :as => :select, :collection => Layer.all, :label => false, :prompt => "Selecione uma Camada" 
    = f.button :submit, "Buscar", :class => "btn"
= @prot_ap
= @prot_tran
= @prot_rede
= @prot_fisico


%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Nome
      %th Descrição
      %th Ações
  %tbody
    - @layers.each do |layer|
      %tr
        %td= link_to layer.id, layer_path(layer)
        %td= layer.name
        %td= layer.description
        %td
          = link_to "Editar", edit_layer_path(layer), :class => 'btn btn-mini'
          = link_to "Deletar", layer_path(layer), :method => :delete, :data => { :confirm => "Tem certeza?" }, :class => 'btn btn-mini btn-danger'
         

= link_to "Nova Camada", new_layer_path, :class => 'btn btn-primary'

app/views/layers/new.html.haml
.page-header
  %h1 Nova Camada
= render :partial => "form"

app/views/layers/show.html.haml
.page-header
  %h1= @layer.name

= simple_format @layer.description
.form-actions
  = link_to "Voltar", layers_path, :class => 'btn'
  = link_to "Editar", edit_layer_path(@layer), :class => 'btn'
  = link_to "Excluir", layer_path(@layer), :method => "delete", :data => { :confirm => "Tem Certeza?" }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Seminario"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Seminario
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", root_path
              %li= link_to "Camadas", layers_path
              %li= link_to "Protocolos", protocols_path
              %li= link_to "Grafico", pages_chart_path
             
             
             
             
              
              
    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav           
            %ul.nav.nav-list
              %li.nav-header Menu
              %li= link_to "Camadas", layers_path
              %li= link_to "Protocolos", protocols_path
              %li= link_to "Novo Protocolo", new_protocol_path
              %li= link_to "Nova Camada", new_layer_path             
    
      %footer
        
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/pages/chart.html.erb
<html>
<head>

 <%= javascript_include_tag :amcharts %> 
 
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <script src="/pages/amcharts.js" type="text/javascript"></script>         
        <script type="text/javascript">
            var chart;

            var chartData = [{
                country: "Aplicação",
                visits: 9
            }, {
                country: "Rede",
                visits: 6
            }, {
                country: "Transporte",
                visits: 3
            }, {
                country: "Internet",
                visits: 4
            }];


            AmCharts.ready(function () {
                // PIE CHART
                chart = new AmCharts.AmPieChart();

                // title of the chart
                chart.addTitle("Gráfico ", 16);

                chart.dataProvider = chartData;
                chart.titleField = "country";
                chart.valueField = "visits";
                chart.sequencedAnimation = true;
                chart.startEffect = "elastic";
                chart.innerRadius = "30%";
                chart.startDuration = 2;
                chart.labelRadius = 15;

                // the following two lines makes the chart 3D
                chart.depth3D = 10;
                chart.angle = 15;

                // WRITE                                 
                chart.write("chartdiv");
            });
        </script>
    </head>
    
    <body>
        <div id="chartdiv" style="width:800px; height:600px;"></div>
			
					
	  </body>
</html>

app/views/protocols/_form.html.haml
= simple_form_for @protocol, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :description, :input_html => { rows: 4 }
  = f.association :layer
  .form-actions
    = f.button :submit, "Cadastrar", :class => 'btn btn-primary'
    = link_to "Cancelar", protocols_path, :class => 'btn'

app/views/protocols/edit.html.haml
- model_class = Protocol
.page-header
  %h1 Editar Protocolo
= render :partial => "form"

app/views/protocols/index.html.haml
.page-header
  %h1 Protocolos
  = simple_form_for :search, :url => protocols_path, :method => :get do |f|
    = f.input :name, :label => false, :input_html => { value: (params[:search][:name] rescue nil) }, :required => false
    = f.input :layer, :as => :select, :collection => Layer.all, :label => false, :prompt => "Selecione uma Camada"
    = f.button :submit, "Buscar", :class => "btn"
%table.table.table-striped
  %thead
    %tr
      %th Nome
      %th Descrição
      %th Camada
  %tbody
    - @protocols.each do |protocol|
      %tr
        %td= protocol.name
        %td= protocol.description
        %td= protocol.layer.name
        %td  
          = link_to "Editar", edit_protocol_path(protocol), :class => 'btn btn-mini'
          = link_to "Deletar", protocol_path(protocol), :method => :delete, :data => { :confirm => "Tem Certeza?" }, :class => 'btn btn-mini btn-danger'

= link_to "Novo Procotolo", new_protocol_path, :class => 'btn btn-primary'

app/views/protocols/new.html.haml
- model_class = Protocol
.page-header
  %h1 Novo Protocolo
= render :partial => "form"

app/views/protocols/show.html.haml
.page-header
  %h1= @protocol.name

= simple_format @protocol.description
.form-actions
  = link_to "Voltar", protocols_path, :class => 'btn'
  = link_to "Editar", edit_protocol_path(@protocol), :class => 'btn'
  = link_to "Excluir", protocol_path(@protocol), :method => "delete", :data => { :confirm => "Tem Certeza?" }, :class => 'btn btn-danger'
  = link_to "Novo Procotolo", new_protocol_path, :class => 'btn btn-primary'